const COURSES = [
  {
    id: "apr-portugues",
    title: "Aprender Português",
    category: "Idiomas",
    description: "Capacitação em linguagem, comunicação clara e aplicação no contexto de loja.",
    cover: "imagens/Aprender portugues.png",
    accessUrl: "https://felipecbitencourt.github.io/aprender-pt/",
    reportUrl: "relatórios/Relatório Técnico-Pedagógico - Aprender Português (1).html",
    changelogUrl: "",
    accent: "var(--pop-emerald)",
    status: "Revisão",
    changelog: {
      demanda: ["Demanda levantada pela area de treinamento para trilha de idiomas."],
      reunioes: ["Reuniao inicial para definicao de escopo e publico-alvo."],
      atualizacoes: ["Ajuste de conteudos e revisao de atividades praticas."],
      aprovacao: ["Aprovado para ciclo atual."],
      timeline: [
        { date: "10/04/2026 09:00", type: "Reunião", colorClass: "type-reuniao", title: "Apresentacao de desenvolvimento do Aprender-PT." },
        { date: "10/04/2026 09:00", type: "Atualização", colorClass: "type-atualizacao", title: "Atualizacao do andamento do projeto apresentada em reuniao." },
        { date: "22/04/2026 10:27", type: "Atualização", colorClass: "type-atualizacao", title: "Envio do Aprender-PT com relatorio tecnico-pedagogico para validacao, alinhamento de expectativas e proposta de workshop com usuarios." },
      ],
    },
  },
  {
    id: "hub-traducoes",
    title: "Hub de Traduções",
    category: "Idiomas",
    description: "Central de traduções para suportar padronização e acesso rápido a conteúdo multilíngue.",
    cover: "imagens/Hub_traduções.png",
    accessUrl: "https://felipecbitencourt.github.io/translate-hub/",
    reportUrl: "relatórios/Relatório Técnico-Pedagógico - Hub de Traduções (1).html",
    changelogUrl: "",
    accent: "var(--pop-tomato)",
    status: "Revisão",
    changelog: {
      demanda: ["Solicitacao para centralizar traducoes em um unico ponto."],
      reunioes: ["Alinhamento com equipe de conteudo e operacao."],
      atualizacoes: ["Inclusao de novos recursos de traducao."],
      aprovacao: ["Aprovado com monitoramento continuo."],
      timeline: [
        { date: "10/04/2026 09:00", type: "Reunião", colorClass: "type-reuniao", title: "Apresentacao de desenvolvimento do Hub de Traducoes." },
        { date: "10/04/2026 09:00", type: "Atualização", colorClass: "type-atualizacao", title: "Atualizacao do andamento do projeto apresentada em reuniao." },
        { date: "15/04/2026 17:24", type: "Atualização", colorClass: "type-atualizacao", title: "Envio do MVP do Hub de Traducoes para validacao inicial." },
        { date: "22/04/2026 10:27", type: "Atualização", colorClass: "type-atualizacao", title: "Reenvio do Hub de Traducoes com relatorio, alinhamento de expectativas e proposta de workshop." },
      ],
    },
  },
  {
    id: "nr17",
    title: "NR-17 Aplicada",
    category: "SAC",
    description: "Boas práticas ergonômicas para rotina operacional, redução de riscos e produtividade.",
    cover: "imagens/nr-17.png",
    accessUrl: "https://felipecbitencourt.github.io/NR17/",
    reportUrl: "relatórios/Relatório NR-17.html",
    changelogUrl: "",
    accent: "var(--pop-navy)",
    status: "Entregue",
    changelog: {
      demanda: ["Necessidade de reforco ergonomico e conformidade operacional."],
      reunioes: ["Reunioes com liderancas para validacao da trilha NR-17."],
      atualizacoes: ["Conteudo revisado para linguagem mais objetiva."],
      aprovacao: ["Entrega final aprovada."],
      timeline: [
        { date: "10/01/2026 10:34", type: "Demanda", colorClass: "type-demanda", title: "Demanda inicial da NR-17: cliente encaminha material base para desenvolvimento do curso voltado ao SAC e Recuperacao de Credito." },
        { date: "10/01/2026 11:59", type: "Atualização", colorClass: "type-atualizacao", title: "Equipe confirma recebimento e solicita reenvio do anexo por falha no envio inicial." },
        { date: "10/01/2026 12:26", type: "Demanda", colorClass: "type-demanda", title: "Cliente reenviou os anexos da NR-17 para continuidade da producao." },
        { date: "26/01/2026 13:07", type: "Atualização", colorClass: "type-atualizacao", title: "Envio da versao do NR-17 para avaliacao da equipe cliente." },
        { date: "26/01/2026 17:25", type: "Demanda", colorClass: "type-demanda", title: "Retorno positivo com observacoes pontuais de terminologia." },
        { date: "27/02/2026 15:51", type: "Demanda", colorClass: "type-demanda", title: "Cliente encaminha PDF com observacoes e necessidades de ajuste do NR-17." },
        { date: "13/03/2026 17:41", type: "Atualização", colorClass: "type-atualizacao", title: "Envio da pasta ZIP atualizada do curso NR-17 para validação." },
        { date: "19/03/2026 16:02", type: "Demanda", colorClass: "type-demanda", title: "Cliente retorna com novos ajustes no NR-17 (módulo 1 e exercícios) para rodada final." },
        { date: "13/03/2026 17:41", type: "Entregue", colorClass: "type-entregue", title: "Ultimo envio registrado do curso NR-17 para os contratantes." },
      ],
    },
  },
  {
    id: "olhar-critico",
    title: "Fato ou Fake",
    category: "Prateleira",
    description: "Treinamento para avaliação crítica de informações e tomada de decisão baseada em evidências.",
    cover: "imagens/olharcritico.png",
    accessUrl: "https://felipecbitencourt.github.io/fato_fake/",
    reportUrl: "relatórios/Relatório_FatoOuFake.html",
    changelogUrl: "",
    accent: "var(--pop-cherry)",
    status: "Revisão",
    changelog: {
      demanda: ["Encaminhamento de demanda do curso Fato ou Fake."],
      reunioes: [],
      atualizacoes: ["Envio do link de acesso do curso.", "Envio do relatório técnico-pedagógico."],
      aprovacao: [],
      timeline: [
        { date: "28/02/2026", type: "Demanda", colorClass: "type-demanda", title: "Encaminhamento de demanda para desenvolvimento do curso Fato ou Fake." },
        { date: "16/03/2026", type: "Atualização", colorClass: "type-atualizacao", title: "Envio do link de acesso do curso para validação." },
        { date: "16/03/2026", type: "Atualização", colorClass: "type-atualizacao", title: "Envio do relatório técnico-pedagógico do curso." },
      ],
    },
  },
  {
    id: "sac",
    code: "SACSAC05",
    title: "Por Dentro do SAC",
    category: "SAC",
    description: "Jornada de atendimento com foco em experiência do cliente, eficiência e qualidade de serviço.",
    cover: "imagens/Por dentro do SAC.png",
    accessUrl: "https://felipecbitencourt.github.io/zaffari/",
    reportUrl: "relatórios/Relatório Por dentro do SAC.html",
    changelogUrl: "",
    accent: "var(--pop-coral)",
    status: "Entregue",
    changelog: {
      demanda: ["Capa Por Dentro do SACSAC05.", "Por Dentro do SAC."],
      reunioes: ["Reunioes com operacao para mapear jornada de atendimento."],
      atualizacoes: ["Entregue.", "Jornada de atendimento com foco em experiência do cliente, eficiência e qualidade de serviço."],
      aprovacao: ["Aprovacao final concluida.", "Acesso liberado para o curso."],
      timeline: [
        { date: "10/12/2025 09:30", type: "Reunião", colorClass: "type-reuniao", title: "Reunião Teams - Cursos Plataforma Transformação para alinhamentos iniciais do Por Dentro do SAC." },
        { date: "18/12/2025 14:19", type: "Atualização", colorClass: "type-atualizacao", title: "Envio do curso SCORM com relatório de funcionalidades e link provisório de acesso, com proposta de reunião de apresentação." },
        { date: "26/12/2025 15:00", type: "Reunião", colorClass: "type-reuniao", title: "Alinhamentos - Curso SAC em reunião do Microsoft Teams." },
        { date: "29/12/2025 08:00", type: "Atualização", colorClass: "type-atualizacao", title: 'Envio de atualização do SCORM "Por Dentro do SAC" com síntese de melhorias e link do pacote para teste na Mobiliza.' },
        { date: "29/12/2025 12:30", type: "Demanda", colorClass: "type-demanda", title: "Cliente reporta observações do suporte Mobiliza (incluindo conclusão em 0%) e solicita ajustes." },
        { date: "02/01/2026 14:23", type: "Atualização", colorClass: "type-atualizacao", title: "Reenvio do curso com correções de conclusão SCORM, progresso e leitura guiada." },
        { date: "05/01/2026 14:03", type: "Demanda", colorClass: "type-demanda", title: "Cliente informa incompatibilidade de formato/pacote e solicita novos ajustes." },
        { date: "06/01/2026 12:16", type: "Atualização", colorClass: "type-atualizacao", title: "Envio de novo link do SCORM com ajuste de empacotamento para compatibilidade da plataforma." },
        { date: "06/01/2026 13:47", type: "Demanda", colorClass: "type-demanda", title: "Cliente informa persistência de erro de formato e solicita novo ajuste." },
        { date: "06/01/2026 15:34", type: "Atualização", colorClass: "type-atualizacao", title: "Reenvio com ajustes no imsmanifest.xml e novo pacote para validação." },
        { date: "06/01/2026 16:09", type: "Demanda", colorClass: "type-demanda", title: "Cliente informa abertura de chamado com engenharia da Mobiliza para análise do problema." },
        { date: "09/01/2026 17:22", type: "Demanda", colorClass: "type-demanda", title: "Cliente confirma funcionamento após ajuste da plataforma e encaminha novas observações para refinamento." },
        { date: "12/01/2026 17:29", type: "Atualização", colorClass: "type-atualizacao", title: "Novo envio com ajustes de leitura automática e acessibilidade." },
        { date: "14/01/2026 15:48", type: "Demanda", colorClass: "type-demanda", title: "Retorno positivo preliminar com validação completa prevista na semana seguinte." },
        { date: "30/01/2026 15:32", type: "Demanda", colorClass: "type-demanda", title: "Consolidação de ajustes finais para Por Dentro do SAC." },
        { date: "05/02/2026 16:39", type: "Atualização", colorClass: "type-atualizacao", title: "Reenvio da versão atualizada para validação final e acesso." },
        { date: "05/02/2026 16:39", type: "Entregue", colorClass: "type-entregue", title: "Ultimo envio registrado do curso Por Dentro do SAC para os contratantes." },
      ],
    },
  },
  {
    id: "promotores",
    title: "Promotores",
    category: "Operacional",
    description: "Padrões operacionais para promotores com orientações objetivas e aplicação no dia a dia.",
    cover: "imagens/promotores.png",
    accessUrl: "https://felipecbitencourt.github.io/Promotoress/",
    reportUrl: "relatórios/Relatório_Promotores.html",
    changelogUrl: "",
    accent: "var(--pop-ink)",
    status: "Entregue",
    changelog: {
      demanda: ["Reforco dos padroes operacionais para promotores."],
      reunioes: ["Alinhamento com lideranca de campo."],
      atualizacoes: ["Conteudo atualizado com novas diretrizes."],
      aprovacao: ["Aprovado para versao atual."],
      timeline: [
        { date: "07/04/2026 08:52", type: "Demanda", colorClass: "type-demanda", title: "Cliente envia devolutiva positiva do material Promotores e encaminha sugestoes de melhoria." },
        { date: "16/04/2026 15:48", type: "Atualização", colorClass: "type-atualizacao", title: "Equipe envia versao atualizada e sinaliza limitacao tecnica sobre legendas por ausencia de arquivo bruto." },
        { date: "22/04/2026 08:47", type: "Demanda", colorClass: "type-demanda", title: "Cliente solicita ajustes finais de texto, atividade e criterios da avaliacao no treinamento." },
        { date: "22/04/2026 11:05", type: "Atualização", colorClass: "type-atualizacao", title: "Correcoes implementadas e nova versao publicada no link de acesso." },
        { date: "22/04/2026 11:16", type: "Entregue", colorClass: "type-entregue", title: "Recebido retorno de confirmacao (\"Obrigada\") apos aplicacao dos ajustes." },
      ],
    },
  },
  {
    id: "contas-a-pagar",
    title: "Contas a Pagar",
    category: "Financeiro",
    description: "Treinamento imersivo do fluxo financeiro: da nota fiscal a conciliacao bancaria no processo de contas a pagar.",
    cover: "imagens/contas-a-pagar.png",
    accessUrl: "https://felipecbitencourt.github.io/Contas-a-Pagar/",
    reportUrl: "",
    changelogUrl: "",
    accent: "var(--brand)",
    status: "Desenvolvimento",
    changelog: {
      demanda: ["Demanda mapeada para trilha financeira."],
      reunioes: ["Reuniao de kickoff pendente."],
      atualizacoes: [],
      aprovacao: [],
      timeline: [
        { date: "27/02/2026 15:51", type: "Demanda", colorClass: "type-demanda", title: "Recebimento do roteiro do curso Contas a Pagar para avaliacao de abordagem." },
      ],
    },
  },
  {
    id: "canais-comunicacao",
    title: "Canais de Comunicação",
    category: "SAC",
    description: "Trilha de comunicacao para atendimento SAC, com foco em canais, boas praticas e experiencia do cliente.",
    cover: "imagens/canais-comunicacao.png",
    accessUrl: "https://dudatess.github.io/sac-micro-2/",
    reportUrl: "relatórios/Relatorio_canais.html",
    changelogUrl: "",
    accent: "var(--pop-coral)",
    status: "Entregue",
    changelog: {
      demanda: ["Demanda para padronizar canais de comunicacao com cliente."],
      reunioes: ["Reunioes de alinhamento com SAC."],
      atualizacoes: ["Fluxos revisados e consolidados."],
      aprovacao: ["Aprovacao final registrada."],
      timeline: [
        { date: "23/01/2026 08:00", type: "Demanda", colorClass: "type-demanda", title: "Envio inicial do microlearning de Canais de Comunicacao para testes." },
        { date: "30/01/2026 15:32", type: "Demanda", colorClass: "type-demanda", title: "Cliente envia observacoes de ajuste apos validacao interna." },
        { date: "27/02/2026 15:51", type: "Demanda", colorClass: "type-demanda", title: "Direcionamento de conteudo e layout para a pagina 'Nosso Sistema'." },
        { date: "03/03/2026 16:16", type: "Atualização", colorClass: "type-atualizacao", title: "Envio da versao atualizada conforme orientacoes recebidas." },
        { date: "13/03/2026 17:41", type: "Atualização", colorClass: "type-atualizacao", title: "Envio da pasta ZIP atualizada do curso Canais de Comunicação para validação." },
        { date: "19/03/2026 16:02", type: "Entregue", colorClass: "type-entregue", title: "Cliente confirma que Canais de Comunicação contemplou os ajustes e está validado." },
        { date: "03/03/2026 16:16", type: "Entregue", colorClass: "type-entregue", title: "Ultimo envio registrado do curso Canais de Comunicacao para os contratantes." },
      ],
    },
  },
  {
    id: "heflo",
    title: "Heflo",
    category: "Operacional",
    description: "Capacitação para modelagem e leitura de processos no Heflo, com foco em padronização operacional.",
    cover: "imagens/v1-hexagonos-inicial.png",
    accessUrl: "https://drive.google.com/drive/folders/1xc7cRoIDxGgy7Kax3DmXnpeDp3dy-L3R?usp=sharing",
    reportUrl: "",
    changelogUrl: "",
    accent: "var(--pop-navy)",
    status: "Desenvolvimento",
    changelog: {
      demanda: ["Apresentação de demanda inicial do projeto Heflo."],
      reunioes: ["Reunião com equipe Heflo para alinhamento de escopo e fluxo."],
      atualizacoes: ["Envio de design e referências visuais para validação."],
      aprovacao: [],
      timeline: [
        { date: "06/02/2026 09:30", type: "Reunião", colorClass: "type-reuniao", title: "Apresentação de demanda." },
        { date: "11/02/2026", type: "Reunião", colorClass: "type-reuniao", title: "Reunião com a equipe Heflo." },
        { date: "20/02/2026", type: "Reunião", colorClass: "type-reuniao", title: "Apresentação de layouts e atualizações." },
        { date: "27/02/2026", type: "Atualização", colorClass: "type-atualizacao", title: "Envio de design para validação (acesso via pasta compartilhada)." },
        { date: "24/03/2026", type: "Demanda", colorClass: "type-demanda", title: "Apresentação de ajustes necessários da demanda." },
      ],
    },
  },
  {
    id: "implementacao-acessibilidade",
    title: "Treinamento Inicial do setor de Hortifruti",
    category: "Acessibilidade",
    description: "Implementação de recursos de acessibilidade no curso inicial de Hortifruti.",
    cover: "imagens/Hortifruti.png",
    accessUrl: "",
    reportUrl: "",
    changelogUrl: "",
    accent: "var(--pop-emerald)",
    status: "Desenvolvimento",
    changelog: {
      demanda: ["Levantamento de cursos para implementação de acessibilidade no acervo existente."],
      reunioes: [],
      atualizacoes: [],
      aprovacao: [],
      timeline: [
        { date: "13/04/2026", type: "Demanda", colorClass: "type-demanda", title: "Discussão acerca da demanda de implementação de acessibilidade no curso." },
        { date: "28/04/2026", type: "Atualização", colorClass: "type-atualizacao", title: "Atualizações acerca das possibilidades de implementação." },
      ],
    },
  },
];

