const COURSES = [
  {
    id: "apr-portugues",
    title: "Aprender Portugues",
    category: "Idiomas",
    description: "Capacitacao em linguagem, comunicacao clara e aplicacao no contexto de loja.",
    cover: "imagens/Aprender portugues.png",
    accessUrl: "https://felipecbitencourt.github.io/aprender-pt/",
    reportUrl: "relatórios/Relatório Técnico-Pedagógico - Aprender Português (1).html",
    changelogUrl: "",
    accent: "var(--pop-emerald)",
    status: "Atualizacoes",
  },
  {
    id: "hub-traducoes",
    title: "Hub de Traducoes",
    category: "Idiomas",
    description: "Central de traducoes para suportar padronizacao e acesso rapido a conteudo multilíngue.",
    cover: "imagens/Hub_traduções.png",
    accessUrl: "https://felipecbitencourt.github.io/translate-hub/",
    reportUrl: "relatórios/Relatório Técnico-Pedagógico - Hub de Traduções (1).html",
    changelogUrl: "",
    accent: "var(--pop-tomato)",
    status: "Atualizacoes",
  },
  {
    id: "nr17",
    title: "NR-17 Aplicada",
    category: "SAC",
    description: "Boas praticas ergonomicas para rotina operacional, reducao de riscos e produtividade.",
    cover: "imagens/nr-17.png",
    accessUrl: "https://felipecbitencourt.github.io/NR17/",
    reportUrl: "relatórios/Relatório NR-17.html",
    changelogUrl: "",
    accent: "var(--pop-navy)",
    status: "Entregue",
  },
  {
    id: "olhar-critico",
    title: "Fato ou Fake",
    category: "Prateleira",
    description: "Treinamento para avaliacao critica de informacoes e tomada de decisao baseada em evidencias.",
    cover: "imagens/olharcritico.png",
    accessUrl: "https://felipecbitencourt.github.io/fato_fake/",
    reportUrl: "relatórios/Relatório_FatoOuFake.html",
    changelogUrl: "",
    accent: "var(--pop-cherry)",
    status: "Atualizacoes",
  },
  {
    id: "sac",
    title: "Por Dentro do SAC",
    category: "SAC",
    description: "Jornada de atendimento com foco em experiencia do cliente, eficiencia e qualidade de servico.",
    cover: "imagens/Por dentro do SAC.png",
    accessUrl: "https://felipecbitencourt.github.io/zaffari/",
    reportUrl: "relatórios/Relatório Por dentro do SAC.html",
    changelogUrl: "",
    accent: "var(--pop-coral)",
    status: "Entregue",
  },
  {
    id: "promotores",
    title: "Promotores",
    category: "Operacional",
    description: "Padroes operacionais para promotores com orientacoes objetivas e aplicacao no dia a dia.",
    cover: "imagens/promotores.png",
    accessUrl: "https://felipecbitencourt.github.io/Promotoress/",
    reportUrl: "relatórios/Relatório_Promotores.html",
    changelogUrl: "",
    accent: "var(--pop-ink)",
    status: "Atualizacoes",
  },
  {
    id: "contas-a-pagar",
    title: "Contas a Pagar",
    category: "Financeiro",
    description: "Placeholder de conteudo para trilha financeira com foco no fluxo de contas a pagar.",
    cover: "",
    accessUrl: "",
    reportUrl: "",
    changelogUrl: "",
    accent: "var(--brand)",
    status: "Desenvolvimento",
  },
  {
    id: "canais-comunicacao",
    title: "Canais de Comunicacao",
    category: "SAC",
    description: "Placeholder para orientar canais, fluxos de contato e padroes de comunicacao com cliente.",
    cover: "",
    accessUrl: "",
    reportUrl: "",
    changelogUrl: "",
    accent: "var(--pop-coral)",
    status: "Entregue",
  },
];

